cmake_minimum_required(VERSION 3.21)
if(EXISTS "${DESTINATION}")
  file(SHA256 "${DESTINATION}" actual)
  if(actual STREQUAL EXPECTED_SHA256)
    return()
  endif()
endif()
file(DOWNLOAD "${URL}" "${DESTINATION}.partial"
  EXPECTED_HASH "SHA256=${EXPECTED_SHA256}" TLS_VERIFY ON STATUS result)
list(GET result 0 status)
list(GET result 1 error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Cannot download pinned sherpa source: ${error}")
endif()
file(RENAME "${DESTINATION}.partial" "${DESTINATION}")
